services:
  tor:
    image: tor-proxy
    container_name: tor-proxy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tor-proxy-net
    
networks:
  tor-proxy-net:
    driver: bridge

