services:
  tor-proxy:
    image: tor-proxy:latest
    container_name: tor-proxy
    build:
      context: .
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/torrc.conf:/etc/tor/torrc:ro
    ports:
      - "8080:80"
    networks:
      - tor-proxy-network
volumes:
  config:

networks:
  tor-proxy-network:
    driver: bridge  