export default class Config {
    // Do not edit this file, instead copy it to
    // config.ts and edit the property values below.
    public Username = "<username here>";
    public Password = "<password here>";

    private static _instance: Config;

    private constructor()
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    {
    }

    public static get Instance(): Config {
        return this._instance || (this._instance = new this());
    }
}
