version: '2.4'
services:
    alarmdotcom:
        stdin_open: true
        tty: true
        build: .
        container_name: alarmdotcom
        image: alarmdotcom:latest
        ports:
         - "9229:9229"
        volumes:
         - .:/usr/app/alarmdotcom
        environment:
         - NODE_ENV=development
         - USEDOCKER=true
        restart: unless-stopped
