services:
  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    container_name: nostr-relay
    ports:
      - "80:80"
    environment:
      - RUST_LOG=info
    volumes:
      - ./relay-data:/usr/src/app/db:rw,z
      - ./relay-logs:/usr/src/app/logs:rw,z
      - ./relay-keys:/usr/src/app/keys:rw,z
      - ./relay-config/config.toml:/usr/src/app/config.toml:ro
    restart: unless-stopped
