version: '3.5'
services:
  spfx-dev:
    ports: 
      - 5432:5432
      - 4321:4321
      - 35729:35729
    volumes:
      - .:/usr/app/spfx
    image: spfx-dev:latest
    stdin_open: true
    tty: true
    build:
      context: .
    container_name: spfx-dev
    restart: always
