ntopng:
  container_name: "ntopng"
  image: vimagick/ntopng
  command: --community -d /var/lib/ntopng -i eth0 -r 127.0.0.1:6379@0 -w 0.0.0.0:3003
  volumes:
    - ./data/ntopng:/var/lib/ntopng
  restart: unless-stopped
  ports:
  - "3003:3003"

redis:
  container_name: "ntopng-redis"
  image: vimagick/ntopng
  image: redis:alpine
  command: --save 900 1
  ports:
    - "6379:6379"
  volumes:
    - ./data/redis:/data
  restart: unless-stopped

