services:

  unifi:
    container_name: "unifi"
    image: jacobalberty/unifi:latest
    volumes:
      - /var/lib/unifi:/var/lib/unifi
    restart: always
    networks:
      - net
    ports:
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8443:8443/tcp"
      - "8880:8880/tcp"
      - "8843:8843/tcp"
      - "3478:3478/udp"

networks:
  net:

